// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrder creates a new instance of MockOrder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrder {
	mock := &MockOrder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrder is an autogenerated mock type for the Order type
type MockOrder struct {
	mock.Mock
}

type MockOrder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrder) EXPECT() *MockOrder_Expecter {
	return &MockOrder_Expecter{mock: &_m.Mock}
}

// GetUserOrders provides a mock function for the type MockOrder
func (_mock *MockOrder) GetUserOrders(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockOrder_GetUserOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserOrders'
type MockOrder_GetUserOrders_Call struct {
	*mock.Call
}

// GetUserOrders is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockOrder_Expecter) GetUserOrders(w interface{}, r interface{}) *MockOrder_GetUserOrders_Call {
	return &MockOrder_GetUserOrders_Call{Call: _e.mock.On("GetUserOrders", w, r)}
}

func (_c *MockOrder_GetUserOrders_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockOrder_GetUserOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrder_GetUserOrders_Call) Return() *MockOrder_GetUserOrders_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOrder_GetUserOrders_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockOrder_GetUserOrders_Call {
	_c.Run(run)
	return _c
}

// UploadUserOrder provides a mock function for the type MockOrder
func (_mock *MockOrder) UploadUserOrder(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockOrder_UploadUserOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadUserOrder'
type MockOrder_UploadUserOrder_Call struct {
	*mock.Call
}

// UploadUserOrder is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockOrder_Expecter) UploadUserOrder(w interface{}, r interface{}) *MockOrder_UploadUserOrder_Call {
	return &MockOrder_UploadUserOrder_Call{Call: _e.mock.On("UploadUserOrder", w, r)}
}

func (_c *MockOrder_UploadUserOrder_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockOrder_UploadUserOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrder_UploadUserOrder_Call) Return() *MockOrder_UploadUserOrder_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOrder_UploadUserOrder_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockOrder_UploadUserOrder_Call {
	_c.Run(run)
	return _c
}
