// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/eshadow1/gophermart/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBalanceServer creates a new instance of MockBalanceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalanceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalanceServer {
	mock := &MockBalanceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBalanceServer is an autogenerated mock type for the BalanceServer type
type MockBalanceServer struct {
	mock.Mock
}

type MockBalanceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBalanceServer) EXPECT() *MockBalanceServer_Expecter {
	return &MockBalanceServer_Expecter{mock: &_m.Mock}
}

// GetBalance provides a mock function for the type MockBalanceServer
func (_mock *MockBalanceServer) GetBalance(context1 context.Context, n int64) (models.BalanceResponse, error) {
	ret := _mock.Called(context1, n)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 models.BalanceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (models.BalanceResponse, error)); ok {
		return returnFunc(context1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) models.BalanceResponse); ok {
		r0 = returnFunc(context1, n)
	} else {
		r0 = ret.Get(0).(models.BalanceResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(context1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBalanceServer_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockBalanceServer_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - context1 context.Context
//   - n int64
func (_e *MockBalanceServer_Expecter) GetBalance(context1 interface{}, n interface{}) *MockBalanceServer_GetBalance_Call {
	return &MockBalanceServer_GetBalance_Call{Call: _e.mock.On("GetBalance", context1, n)}
}

func (_c *MockBalanceServer_GetBalance_Call) Run(run func(context1 context.Context, n int64)) *MockBalanceServer_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalanceServer_GetBalance_Call) Return(balanceResponse models.BalanceResponse, err error) *MockBalanceServer_GetBalance_Call {
	_c.Call.Return(balanceResponse, err)
	return _c
}

func (_c *MockBalanceServer_GetBalance_Call) RunAndReturn(run func(context1 context.Context, n int64) (models.BalanceResponse, error)) *MockBalanceServer_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// ListWithdrawals provides a mock function for the type MockBalanceServer
func (_mock *MockBalanceServer) ListWithdrawals(context1 context.Context, n int64) ([]models.WithdrawalResponse, error) {
	ret := _mock.Called(context1, n)

	if len(ret) == 0 {
		panic("no return value specified for ListWithdrawals")
	}

	var r0 []models.WithdrawalResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]models.WithdrawalResponse, error)); ok {
		return returnFunc(context1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []models.WithdrawalResponse); ok {
		r0 = returnFunc(context1, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WithdrawalResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(context1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBalanceServer_ListWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWithdrawals'
type MockBalanceServer_ListWithdrawals_Call struct {
	*mock.Call
}

// ListWithdrawals is a helper method to define mock.On call
//   - context1 context.Context
//   - n int64
func (_e *MockBalanceServer_Expecter) ListWithdrawals(context1 interface{}, n interface{}) *MockBalanceServer_ListWithdrawals_Call {
	return &MockBalanceServer_ListWithdrawals_Call{Call: _e.mock.On("ListWithdrawals", context1, n)}
}

func (_c *MockBalanceServer_ListWithdrawals_Call) Run(run func(context1 context.Context, n int64)) *MockBalanceServer_ListWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalanceServer_ListWithdrawals_Call) Return(withdrawalResponses []models.WithdrawalResponse, err error) *MockBalanceServer_ListWithdrawals_Call {
	_c.Call.Return(withdrawalResponses, err)
	return _c
}

func (_c *MockBalanceServer_ListWithdrawals_Call) RunAndReturn(run func(context1 context.Context, n int64) ([]models.WithdrawalResponse, error)) *MockBalanceServer_ListWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// RequestWithdraw provides a mock function for the type MockBalanceServer
func (_mock *MockBalanceServer) RequestWithdraw(context1 context.Context, n int64, withdrawRequest models.WithdrawRequest) error {
	ret := _mock.Called(context1, n, withdrawRequest)

	if len(ret) == 0 {
		panic("no return value specified for RequestWithdraw")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, models.WithdrawRequest) error); ok {
		r0 = returnFunc(context1, n, withdrawRequest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBalanceServer_RequestWithdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestWithdraw'
type MockBalanceServer_RequestWithdraw_Call struct {
	*mock.Call
}

// RequestWithdraw is a helper method to define mock.On call
//   - context1 context.Context
//   - n int64
//   - withdrawRequest models.WithdrawRequest
func (_e *MockBalanceServer_Expecter) RequestWithdraw(context1 interface{}, n interface{}, withdrawRequest interface{}) *MockBalanceServer_RequestWithdraw_Call {
	return &MockBalanceServer_RequestWithdraw_Call{Call: _e.mock.On("RequestWithdraw", context1, n, withdrawRequest)}
}

func (_c *MockBalanceServer_RequestWithdraw_Call) Run(run func(context1 context.Context, n int64, withdrawRequest models.WithdrawRequest)) *MockBalanceServer_RequestWithdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 models.WithdrawRequest
		if args[2] != nil {
			arg2 = args[2].(models.WithdrawRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBalanceServer_RequestWithdraw_Call) Return(err error) *MockBalanceServer_RequestWithdraw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBalanceServer_RequestWithdraw_Call) RunAndReturn(run func(context1 context.Context, n int64, withdrawRequest models.WithdrawRequest) error) *MockBalanceServer_RequestWithdraw_Call {
	_c.Call.Return(run)
	return _c
}
