// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthHandler creates a new instance of MockAuthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthHandler {
	mock := &MockAuthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthHandler is an autogenerated mock type for the AuthHandler type
type MockAuthHandler struct {
	mock.Mock
}

type MockAuthHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthHandler) EXPECT() *MockAuthHandler_Expecter {
	return &MockAuthHandler_Expecter{mock: &_m.Mock}
}

// LoginUser provides a mock function for the type MockAuthHandler
func (_mock *MockAuthHandler) LoginUser(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockAuthHandler_LoginUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginUser'
type MockAuthHandler_LoginUser_Call struct {
	*mock.Call
}

// LoginUser is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockAuthHandler_Expecter) LoginUser(w interface{}, r interface{}) *MockAuthHandler_LoginUser_Call {
	return &MockAuthHandler_LoginUser_Call{Call: _e.mock.On("LoginUser", w, r)}
}

func (_c *MockAuthHandler_LoginUser_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockAuthHandler_LoginUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthHandler_LoginUser_Call) Return() *MockAuthHandler_LoginUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuthHandler_LoginUser_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockAuthHandler_LoginUser_Call {
	_c.Run(run)
	return _c
}

// RegisterUser provides a mock function for the type MockAuthHandler
func (_mock *MockAuthHandler) RegisterUser(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockAuthHandler_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockAuthHandler_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockAuthHandler_Expecter) RegisterUser(w interface{}, r interface{}) *MockAuthHandler_RegisterUser_Call {
	return &MockAuthHandler_RegisterUser_Call{Call: _e.mock.On("RegisterUser", w, r)}
}

func (_c *MockAuthHandler_RegisterUser_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockAuthHandler_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthHandler_RegisterUser_Call) Return() *MockAuthHandler_RegisterUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuthHandler_RegisterUser_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockAuthHandler_RegisterUser_Call {
	_c.Run(run)
	return _c
}
