// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBalance creates a new instance of MockBalance. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalance(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalance {
	mock := &MockBalance{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBalance is an autogenerated mock type for the Balance type
type MockBalance struct {
	mock.Mock
}

type MockBalance_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBalance) EXPECT() *MockBalance_Expecter {
	return &MockBalance_Expecter{mock: &_m.Mock}
}

// GetBalanceUser provides a mock function for the type MockBalance
func (_mock *MockBalance) GetBalanceUser(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockBalance_GetBalanceUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalanceUser'
type MockBalance_GetBalanceUser_Call struct {
	*mock.Call
}

// GetBalanceUser is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockBalance_Expecter) GetBalanceUser(w interface{}, r interface{}) *MockBalance_GetBalanceUser_Call {
	return &MockBalance_GetBalanceUser_Call{Call: _e.mock.On("GetBalanceUser", w, r)}
}

func (_c *MockBalance_GetBalanceUser_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockBalance_GetBalanceUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalance_GetBalanceUser_Call) Return() *MockBalance_GetBalanceUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBalance_GetBalanceUser_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockBalance_GetBalanceUser_Call {
	_c.Run(run)
	return _c
}

// GetInfoWithdrawals provides a mock function for the type MockBalance
func (_mock *MockBalance) GetInfoWithdrawals(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockBalance_GetInfoWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInfoWithdrawals'
type MockBalance_GetInfoWithdrawals_Call struct {
	*mock.Call
}

// GetInfoWithdrawals is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockBalance_Expecter) GetInfoWithdrawals(w interface{}, r interface{}) *MockBalance_GetInfoWithdrawals_Call {
	return &MockBalance_GetInfoWithdrawals_Call{Call: _e.mock.On("GetInfoWithdrawals", w, r)}
}

func (_c *MockBalance_GetInfoWithdrawals_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockBalance_GetInfoWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalance_GetInfoWithdrawals_Call) Return() *MockBalance_GetInfoWithdrawals_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBalance_GetInfoWithdrawals_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockBalance_GetInfoWithdrawals_Call {
	_c.Run(run)
	return _c
}

// RequestWithdraw provides a mock function for the type MockBalance
func (_mock *MockBalance) RequestWithdraw(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockBalance_RequestWithdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestWithdraw'
type MockBalance_RequestWithdraw_Call struct {
	*mock.Call
}

// RequestWithdraw is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockBalance_Expecter) RequestWithdraw(w interface{}, r interface{}) *MockBalance_RequestWithdraw_Call {
	return &MockBalance_RequestWithdraw_Call{Call: _e.mock.On("RequestWithdraw", w, r)}
}

func (_c *MockBalance_RequestWithdraw_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockBalance_RequestWithdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalance_RequestWithdraw_Call) Return() *MockBalance_RequestWithdraw_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBalance_RequestWithdraw_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockBalance_RequestWithdraw_Call {
	_c.Run(run)
	return _c
}
