// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"context"

	"github.com/eshadow1/gophermart/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderServer creates a new instance of MockOrderServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderServer {
	mock := &MockOrderServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderServer is an autogenerated mock type for the OrderServer type
type MockOrderServer struct {
	mock.Mock
}

type MockOrderServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderServer) EXPECT() *MockOrderServer_Expecter {
	return &MockOrderServer_Expecter{mock: &_m.Mock}
}

// GetUserOrders provides a mock function for the type MockOrderServer
func (_mock *MockOrderServer) GetUserOrders(context1 context.Context, n int64) ([]models.OrderResponse, error) {
	ret := _mock.Called(context1, n)

	if len(ret) == 0 {
		panic("no return value specified for GetUserOrders")
	}

	var r0 []models.OrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]models.OrderResponse, error)); ok {
		return returnFunc(context1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []models.OrderResponse); ok {
		r0 = returnFunc(context1, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(context1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderServer_GetUserOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserOrders'
type MockOrderServer_GetUserOrders_Call struct {
	*mock.Call
}

// GetUserOrders is a helper method to define mock.On call
//   - context1 context.Context
//   - n int64
func (_e *MockOrderServer_Expecter) GetUserOrders(context1 interface{}, n interface{}) *MockOrderServer_GetUserOrders_Call {
	return &MockOrderServer_GetUserOrders_Call{Call: _e.mock.On("GetUserOrders", context1, n)}
}

func (_c *MockOrderServer_GetUserOrders_Call) Run(run func(context1 context.Context, n int64)) *MockOrderServer_GetUserOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderServer_GetUserOrders_Call) Return(orderResponses []models.OrderResponse, err error) *MockOrderServer_GetUserOrders_Call {
	_c.Call.Return(orderResponses, err)
	return _c
}

func (_c *MockOrderServer_GetUserOrders_Call) RunAndReturn(run func(context1 context.Context, n int64) ([]models.OrderResponse, error)) *MockOrderServer_GetUserOrders_Call {
	_c.Call.Return(run)
	return _c
}

// LoadUserOrder provides a mock function for the type MockOrderServer
func (_mock *MockOrderServer) LoadUserOrder(context1 context.Context, n int64, s string) (bool, error) {
	ret := _mock.Called(context1, n, s)

	if len(ret) == 0 {
		panic("no return value specified for LoadUserOrder")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (bool, error)); ok {
		return returnFunc(context1, n, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) bool); ok {
		r0 = returnFunc(context1, n, s)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(context1, n, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderServer_LoadUserOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadUserOrder'
type MockOrderServer_LoadUserOrder_Call struct {
	*mock.Call
}

// LoadUserOrder is a helper method to define mock.On call
//   - context1 context.Context
//   - n int64
//   - s string
func (_e *MockOrderServer_Expecter) LoadUserOrder(context1 interface{}, n interface{}, s interface{}) *MockOrderServer_LoadUserOrder_Call {
	return &MockOrderServer_LoadUserOrder_Call{Call: _e.mock.On("LoadUserOrder", context1, n, s)}
}

func (_c *MockOrderServer_LoadUserOrder_Call) Run(run func(context1 context.Context, n int64, s string)) *MockOrderServer_LoadUserOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderServer_LoadUserOrder_Call) Return(b bool, err error) *MockOrderServer_LoadUserOrder_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockOrderServer_LoadUserOrder_Call) RunAndReturn(run func(context1 context.Context, n int64, s string) (bool, error)) *MockOrderServer_LoadUserOrder_Call {
	_c.Call.Return(run)
	return _c
}
