// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package worker

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBalanceRepo creates a new instance of MockBalanceRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalanceRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalanceRepo {
	mock := &MockBalanceRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBalanceRepo is an autogenerated mock type for the BalanceRepo type
type MockBalanceRepo struct {
	mock.Mock
}

type MockBalanceRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBalanceRepo) EXPECT() *MockBalanceRepo_Expecter {
	return &MockBalanceRepo_Expecter{mock: &_m.Mock}
}

// AddAccrual provides a mock function for the type MockBalanceRepo
func (_mock *MockBalanceRepo) AddAccrual(ctx context.Context, userID int64, amount float64) error {
	ret := _mock.Called(ctx, userID, amount)

	if len(ret) == 0 {
		panic("no return value specified for AddAccrual")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, float64) error); ok {
		r0 = returnFunc(ctx, userID, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBalanceRepo_AddAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAccrual'
type MockBalanceRepo_AddAccrual_Call struct {
	*mock.Call
}

// AddAccrual is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - amount float64
func (_e *MockBalanceRepo_Expecter) AddAccrual(ctx interface{}, userID interface{}, amount interface{}) *MockBalanceRepo_AddAccrual_Call {
	return &MockBalanceRepo_AddAccrual_Call{Call: _e.mock.On("AddAccrual", ctx, userID, amount)}
}

func (_c *MockBalanceRepo_AddAccrual_Call) Run(run func(ctx context.Context, userID int64, amount float64)) *MockBalanceRepo_AddAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBalanceRepo_AddAccrual_Call) Return(err error) *MockBalanceRepo_AddAccrual_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBalanceRepo_AddAccrual_Call) RunAndReturn(run func(ctx context.Context, userID int64, amount float64) error) *MockBalanceRepo_AddAccrual_Call {
	_c.Call.Return(run)
	return _c
}
