// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package worker

import (
	"context"

	"github.com/eshadow1/gophermart/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRepo creates a new instance of MockOrderRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepo {
	mock := &MockOrderRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepo is an autogenerated mock type for the OrderRepo type
type MockOrderRepo struct {
	mock.Mock
}

type MockOrderRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepo) EXPECT() *MockOrderRepo_Expecter {
	return &MockOrderRepo_Expecter{mock: &_m.Mock}
}

// FetchPendingOrders provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) FetchPendingOrders(ctx context.Context, limit int) ([]repository.PendingOrder, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchPendingOrders")
	}

	var r0 []repository.PendingOrder
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]repository.PendingOrder, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []repository.PendingOrder); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.PendingOrder)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepo_FetchPendingOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPendingOrders'
type MockOrderRepo_FetchPendingOrders_Call struct {
	*mock.Call
}

// FetchPendingOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockOrderRepo_Expecter) FetchPendingOrders(ctx interface{}, limit interface{}) *MockOrderRepo_FetchPendingOrders_Call {
	return &MockOrderRepo_FetchPendingOrders_Call{Call: _e.mock.On("FetchPendingOrders", ctx, limit)}
}

func (_c *MockOrderRepo_FetchPendingOrders_Call) Run(run func(ctx context.Context, limit int)) *MockOrderRepo_FetchPendingOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepo_FetchPendingOrders_Call) Return(pendingOrders []repository.PendingOrder, err error) *MockOrderRepo_FetchPendingOrders_Call {
	_c.Call.Return(pendingOrders, err)
	return _c
}

func (_c *MockOrderRepo_FetchPendingOrders_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]repository.PendingOrder, error)) *MockOrderRepo_FetchPendingOrders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderStatus provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) UpdateOrderStatus(ctx context.Context, number string, status string, accrual *float64) error {
	ret := _mock.Called(ctx, number, status, accrual)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *float64) error); ok {
		r0 = returnFunc(ctx, number, status, accrual)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepo_UpdateOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderStatus'
type MockOrderRepo_UpdateOrderStatus_Call struct {
	*mock.Call
}

// UpdateOrderStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
//   - status string
//   - accrual *float64
func (_e *MockOrderRepo_Expecter) UpdateOrderStatus(ctx interface{}, number interface{}, status interface{}, accrual interface{}) *MockOrderRepo_UpdateOrderStatus_Call {
	return &MockOrderRepo_UpdateOrderStatus_Call{Call: _e.mock.On("UpdateOrderStatus", ctx, number, status, accrual)}
}

func (_c *MockOrderRepo_UpdateOrderStatus_Call) Run(run func(ctx context.Context, number string, status string, accrual *float64)) *MockOrderRepo_UpdateOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *float64
		if args[3] != nil {
			arg3 = args[3].(*float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrderRepo_UpdateOrderStatus_Call) Return(err error) *MockOrderRepo_UpdateOrderStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepo_UpdateOrderStatus_Call) RunAndReturn(run func(ctx context.Context, number string, status string, accrual *float64) error) *MockOrderRepo_UpdateOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}
