// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/eshadow1/gophermart/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBalanceRepo creates a new instance of MockBalanceRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalanceRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalanceRepo {
	mock := &MockBalanceRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBalanceRepo is an autogenerated mock type for the BalanceRepo type
type MockBalanceRepo struct {
	mock.Mock
}

type MockBalanceRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBalanceRepo) EXPECT() *MockBalanceRepo_Expecter {
	return &MockBalanceRepo_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockBalanceRepo
func (_mock *MockBalanceRepo) Get(context1 context.Context, n int64) (models.BalanceResponse, error) {
	ret := _mock.Called(context1, n)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.BalanceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (models.BalanceResponse, error)); ok {
		return returnFunc(context1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) models.BalanceResponse); ok {
		r0 = returnFunc(context1, n)
	} else {
		r0 = ret.Get(0).(models.BalanceResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(context1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBalanceRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBalanceRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - n int64
func (_e *MockBalanceRepo_Expecter) Get(context1 interface{}, n interface{}) *MockBalanceRepo_Get_Call {
	return &MockBalanceRepo_Get_Call{Call: _e.mock.On("Get", context1, n)}
}

func (_c *MockBalanceRepo_Get_Call) Run(run func(context1 context.Context, n int64)) *MockBalanceRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalanceRepo_Get_Call) Return(balanceResponse models.BalanceResponse, err error) *MockBalanceRepo_Get_Call {
	_c.Call.Return(balanceResponse, err)
	return _c
}

func (_c *MockBalanceRepo_Get_Call) RunAndReturn(run func(context1 context.Context, n int64) (models.BalanceResponse, error)) *MockBalanceRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListWithdrawals provides a mock function for the type MockBalanceRepo
func (_mock *MockBalanceRepo) ListWithdrawals(context1 context.Context, n int64) ([]models.WithdrawalResponse, error) {
	ret := _mock.Called(context1, n)

	if len(ret) == 0 {
		panic("no return value specified for ListWithdrawals")
	}

	var r0 []models.WithdrawalResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]models.WithdrawalResponse, error)); ok {
		return returnFunc(context1, n)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []models.WithdrawalResponse); ok {
		r0 = returnFunc(context1, n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WithdrawalResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(context1, n)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBalanceRepo_ListWithdrawals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWithdrawals'
type MockBalanceRepo_ListWithdrawals_Call struct {
	*mock.Call
}

// ListWithdrawals is a helper method to define mock.On call
//   - context1 context.Context
//   - n int64
func (_e *MockBalanceRepo_Expecter) ListWithdrawals(context1 interface{}, n interface{}) *MockBalanceRepo_ListWithdrawals_Call {
	return &MockBalanceRepo_ListWithdrawals_Call{Call: _e.mock.On("ListWithdrawals", context1, n)}
}

func (_c *MockBalanceRepo_ListWithdrawals_Call) Run(run func(context1 context.Context, n int64)) *MockBalanceRepo_ListWithdrawals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalanceRepo_ListWithdrawals_Call) Return(withdrawalResponses []models.WithdrawalResponse, err error) *MockBalanceRepo_ListWithdrawals_Call {
	_c.Call.Return(withdrawalResponses, err)
	return _c
}

func (_c *MockBalanceRepo_ListWithdrawals_Call) RunAndReturn(run func(context1 context.Context, n int64) ([]models.WithdrawalResponse, error)) *MockBalanceRepo_ListWithdrawals_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function for the type MockBalanceRepo
func (_mock *MockBalanceRepo) Withdraw(context1 context.Context, n int64, withdrawRequest models.WithdrawRequest) error {
	ret := _mock.Called(context1, n, withdrawRequest)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, models.WithdrawRequest) error); ok {
		r0 = returnFunc(context1, n, withdrawRequest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBalanceRepo_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type MockBalanceRepo_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - context1 context.Context
//   - n int64
//   - withdrawRequest models.WithdrawRequest
func (_e *MockBalanceRepo_Expecter) Withdraw(context1 interface{}, n interface{}, withdrawRequest interface{}) *MockBalanceRepo_Withdraw_Call {
	return &MockBalanceRepo_Withdraw_Call{Call: _e.mock.On("Withdraw", context1, n, withdrawRequest)}
}

func (_c *MockBalanceRepo_Withdraw_Call) Run(run func(context1 context.Context, n int64, withdrawRequest models.WithdrawRequest)) *MockBalanceRepo_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 models.WithdrawRequest
		if args[2] != nil {
			arg2 = args[2].(models.WithdrawRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBalanceRepo_Withdraw_Call) Return(err error) *MockBalanceRepo_Withdraw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBalanceRepo_Withdraw_Call) RunAndReturn(run func(context1 context.Context, n int64, withdrawRequest models.WithdrawRequest) error) *MockBalanceRepo_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}
