// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/eshadow1/gophermart/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRepo creates a new instance of MockOrderRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepo {
	mock := &MockOrderRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepo is an autogenerated mock type for the OrderRepo type
type MockOrderRepo struct {
	mock.Mock
}

type MockOrderRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepo) EXPECT() *MockOrderRepo_Expecter {
	return &MockOrderRepo_Expecter{mock: &_m.Mock}
}

// AddOrder provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) AddOrder(ctx context.Context, userID int64, rawBody string) (bool, error) {
	ret := _mock.Called(ctx, userID, rawBody)

	if len(ret) == 0 {
		panic("no return value specified for AddOrder")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (bool, error)); ok {
		return returnFunc(ctx, userID, rawBody)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) bool); ok {
		r0 = returnFunc(ctx, userID, rawBody)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, rawBody)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepo_AddOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOrder'
type MockOrderRepo_AddOrder_Call struct {
	*mock.Call
}

// AddOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - rawBody string
func (_e *MockOrderRepo_Expecter) AddOrder(ctx interface{}, userID interface{}, rawBody interface{}) *MockOrderRepo_AddOrder_Call {
	return &MockOrderRepo_AddOrder_Call{Call: _e.mock.On("AddOrder", ctx, userID, rawBody)}
}

func (_c *MockOrderRepo_AddOrder_Call) Run(run func(ctx context.Context, userID int64, rawBody string)) *MockOrderRepo_AddOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderRepo_AddOrder_Call) Return(b bool, err error) *MockOrderRepo_AddOrder_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockOrderRepo_AddOrder_Call) RunAndReturn(run func(ctx context.Context, userID int64, rawBody string) (bool, error)) *MockOrderRepo_AddOrder_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) ListByUser(ctx context.Context, userID int64) ([]models.OrderResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []models.OrderResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]models.OrderResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []models.OrderResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.OrderResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepo_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockOrderRepo_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockOrderRepo_Expecter) ListByUser(ctx interface{}, userID interface{}) *MockOrderRepo_ListByUser_Call {
	return &MockOrderRepo_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockOrderRepo_ListByUser_Call) Run(run func(ctx context.Context, userID int64)) *MockOrderRepo_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepo_ListByUser_Call) Return(orderResponses []models.OrderResponse, err error) *MockOrderRepo_ListByUser_Call {
	_c.Call.Return(orderResponses, err)
	return _c
}

func (_c *MockOrderRepo_ListByUser_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]models.OrderResponse, error)) *MockOrderRepo_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}
